# Generated by Django 3.2.23 on 2024-01-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientcategory',
            options={'verbose_name': 'Ingredient Category', 'verbose_name_plural': 'Ingredient Categories'},
        ),
    ]
