# Generated by Django 3.2.23 on 2024-01-08 20:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_portal', '0002_alter_ingredientcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('has_tomato', models.BooleanField(default=False)),
                ('has_mozzarella', models.BooleanField(default=False)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('ingredients', models.ManyToManyField(blank=True, to='staff_portal.Ingredient')),
            ],
        ),
    ]
