# Generated by Django 3.2.23 on 2024-01-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_portal', '0003_pizza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Pizza', 'verbose_name_plural': 'Pizzas'},
        ),
    ]
