# Generated by Django 3.2.23 on 2024-01-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_portal', '0005_alter_pizza_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Ingredient Category', 'verbose_name_plural': 'Ingredient Categories'},
        ),
        migrations.AddField(
            model_name='ingredientcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
