# Generated by Django 3.2.23 on 2024-01-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_portal', '0006_auto_20240126_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='origin',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
