# Generated by Django 3.2.23 on 2024-01-11 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_adminn_customstaffuser_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customstaffuser',
            options={'verbose_name': 'Staff User', 'verbose_name_plural': 'Staff Users'},
        ),
    ]
