# Generated by Django 3.2.23 on 2024-02-10 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customstaffuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customstaffuser',
            name='username',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
